# Generated by Django 3.2.2 on 2021-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='per_price',
            field=models.PositiveIntegerField(),
        ),
    ]
