# Generated by Django 3.2.2 on 2021-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0002_alter_food_per_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_img',
            field=models.ImageField(default='default.jpg', upload_to='food_pics'),
        ),
    ]
