# Generated by Django 3.2.2 on 2021-08-19 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0004_auto_20210817_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='rms_app.invoice'),
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='items',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='items',
            field=models.ManyToManyField(related_name='invoice_items', to='rms_app.Food'),
        ),
    ]
