# Generated by Django 3.2.2 on 2021-08-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0005_auto_20210819_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='total',
            new_name='accumulated',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='items',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_invoice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rms_app.food'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='rms_app.invoice'),
        ),
    ]
